import 'package:ui_demo/model/tour_data_model.dart';

List<TourPlace> tourPlaceList = [
  TourPlace(uid: '1', img: 'https://res.cloudinary.com/rainforest-cruises/images/c_fill,g_auto/f_auto,q_auto/w_1120,h_732,c_fill,g_auto/v1661186669/top-10-tourist-attractions-in-india-taj-mahal-building/top-10-tourist-attractions-in-india-taj-mahal-building-1120x732.jpg', name: 'The Taj Mahal', tag: '@agra', description: 'There are few sights in the world as iconic as the Taj Mahal, which is a must-see on most India itineraries, particularly for travelers on the famous Golden Triangle circuit, linking Delhi, Agra, and Jaipur. A testament to the power of an emperor’s love, this astonishingly beautiful mausoleum was named after Mumtaz Mahal, who was the favorite wife of Shah Jahan.'),
  TourPlace(uid: '2', img: 'https://res.cloudinary.com/rainforest-cruises/images/c_fill,g_auto/f_auto,q_auto/w_1120,h_732,c_fill,g_auto/v1661186664/top-10-tourist-attractions-in-india-red-fort/top-10-tourist-attractions-in-india-red-fort-1120x732.jpg', name: 'The Red Fort', tag: '@newdelhi', description: 'New Delhi’s colossal, crescent-shaped Red Fort, named after the stunning red sandstone that was used in its construction, was built by Shah Jahan in 1648. Also called Lal Qalʿah, it was home to emperors of the formidable Mughal dynasty for almost 200 years, until 1857 when the British took over. It covers a vast area of 254.67 acres ringed by one and a half miles of defensive walls, enclosing a complex of palaces and entertainment halls, projecting balconies, baths and indoor canals, and geometrical gardens, as well as an ornate mosque.'),
  TourPlace(uid: '3', img: 'https://res.cloudinary.com/rainforest-cruises/images/c_fill,g_auto/f_auto,q_auto/w_1120,h_732,c_fill,g_auto/v1661186675/top-10-tourist-attractions-in-indiaa-gateway-of-india/top-10-tourist-attractions-in-indiaa-gateway-of-india-1120x732.jpg', name: 'The Gateway of India', tag: '@mumbai', description: 'Standing an impressive 85 feet tall and located on the waterfront at Mumbai Harbour on the tip of Apollo Bunder, overlooking the Arabian Sea, the iconic Gateway of India is a bold yellow basalt arch of colonial triumph and a must-see when in Mumbai. Incorporating Islamic styles of 16th-century Gujarat, it was built to commemorate the arrival of King George V and his wife Queen Mary in 1911 and was opened with much pomp and ceremony in 1924. It was, for a while, the tallest structure in the city.'),
  TourPlace(uid: '4', img: 'https://res.cloudinary.com/rainforest-cruises/images/c_fill,g_auto/f_auto,q_auto/w_1120,h_732,c_fill,g_auto/v1661186642/top-10-tourist-attractions-in-india-amber-fort/top-10-tourist-attractions-in-india-amber-fort-1120x732.jpg', name: 'Amber Palace', tag: '@jaipur', description: 'Amber Palace or Amber Fort, also spelt Amer, was built as a fortified palace in 1592 by Maharaja Man Singh I and has long served as the capital of Jaipur. Carved high up into the hillside, the fort is accessible on foot via a steep climb from the town below. You will enter Amber Fort through the Sun Gate (Suraj Pol), which leads to the Jaleb Chowk, the first courtyard, with its many decorated elephants, and the Shila Devi Temple, dedicated to the goddess of war.'),
  TourPlace(uid: '5', img: 'https://res.cloudinary.com/rainforest-cruises/images/c_fill,g_auto/f_auto,q_auto/w_1120,h_732,c_fill,g_auto/v1661186635/top-10-tourist-attractions-in-india-agra-fort/top-10-tourist-attractions-in-india-agra-fort-1120x732.jpg', name: 'Agra Fort', tag: '@agra', description: 'With the Taj Mahal located so close by, it is easy to forget that Agra has one of the finest Mughal forts in India. Built as a military structure in 1565 by Emperor Akbar with later additions by Shah Jahan, Agra’s Red Fort is an interesting mix of both Hindu and Muslim influences. The fort is entered through Amar Singh Gate with its low outer wall and dogleg design built to confuse attackers, and you can expect to be truly amazed as you walk through courtyard after courtyard of this palatial red-sandstone and marble fortress.'),
  TourPlace(uid: '6', img: 'https://res.cloudinary.com/rainforest-cruises/images/c_fill,g_auto/f_auto,q_auto/w_1120,h_732,c_fill,g_auto/v1661186639/top-10-tourist-attractions-in-india-ajanta-caves/top-10-tourist-attractions-in-india-ajanta-caves-1120x732.jpg', name: 'Ajanta Caves', tag: '@ajanta', description: 'The magnificent Ajanta Caves are rock-cut cave monuments excavated out of a vertical cliff above the left bank of the River Waghora in the hills of Ajanta in the Aurangabad district of India’s Maharashtra state. They are thirty in number, including the unfinished ones, connected with the river by rock-cut staircases. Dating from the 2nd century BCE to about 480 CE, they were abandoned around 650 AD and forgotten until 1819, when a British hunting party stumbled upon them.'),
];